import { AmbientEffect } from './AmbientEffect'
import { CallToAction } from './CallToAction'
import { Countdown } from './Countdown'
import { Gallery } from './Gallery'
import { MusicControl } from './MusicControl'
import PropTypes from 'prop-types'
function InvitationDetails({ event }) { return <section className="content-section event-details" aria-labelledby="event-title"><p className="section-kicker">La celebración</p><h2 id="event-title">{event.dateLabel}</h2><p className="event-time">{event.timeLabel}</p>{event.countdown?.enabled && <Countdown config={event.countdown} />}<div className="details-grid">{event.location && <article><h3>{event.location.venue}</h3><p>{event.location.address}</p>{event.location.directionsUrl && <a href={event.location.directionsUrl} target="_blank" rel="noreferrer noopener">Ver indicaciones</a>}</article>}{event.dressCode && <article><h3>Dress code</h3><p>{event.dressCode}</p></article>}</div></section> }
InvitationDetails.propTypes = { event: PropTypes.shape({ dateLabel: PropTypes.string.isRequired, timeLabel: PropTypes.string.isRequired, countdown: PropTypes.shape({ enabled: PropTypes.bool, target: PropTypes.string }), location: PropTypes.shape({ venue: PropTypes.string, address: PropTypes.string, directionsUrl: PropTypes.string }), dressCode: PropTypes.string }).isRequired }
export function ExperiencePage({ config }) { const invitation = config.mode === 'invitation'; return <main className={`experience theme--${config.theme}`}><AmbientEffect effect={config.effects} /><header className="topbar"><a className="brand" href="?experience=romantic">Special Moments</a><nav aria-label="Seleccionar demostración"><a href="?experience=romantic" aria-current={config.id === 'romantic' ? 'page' : undefined}>Regalo</a><a href="?experience=invitation" aria-current={config.id === 'invitation' ? 'page' : undefined}>Invitación</a></nav></header><section className="hero"><p className="eyebrow">{config.hero.eyebrow}</p><h1>{config.hero.title}</h1><p className="hero-subtitle">{config.hero.subtitle}</p><p className="hero-from">{invitation ? config.identity.hosts : config.identity.sender}</p><CallToAction cta={config.cta} /></section>{invitation ? <InvitationDetails event={config.event} /> : <section className="content-section dedication" aria-labelledby="dedication-title"><p className="section-kicker">Una dedicatoria</p><h2 id="dedication-title">{config.dedication.title}</h2><p>{config.dedication.message}</p></section>}<Gallery gallery={config.gallery} /><footer className="footer">Diseñado para celebrar momentos que importan.</footer><MusicControl music={config.music} /></main> }

ExperiencePage.propTypes = { config: PropTypes.shape({ id: PropTypes.string.isRequired, mode: PropTypes.string.isRequired, theme: PropTypes.string.isRequired, effects: PropTypes.object, hero: PropTypes.shape({ eyebrow: PropTypes.string.isRequired, title: PropTypes.string.isRequired, subtitle: PropTypes.string.isRequired }).isRequired, identity: PropTypes.shape({ hosts: PropTypes.string, sender: PropTypes.string }).isRequired, cta: PropTypes.object, event: PropTypes.object, dedication: PropTypes.shape({ title: PropTypes.string, message: PropTypes.string }), gallery: PropTypes.object, music: PropTypes.object }).isRequired }
